# Generated by Django 5.1.7 on 2025-03-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('copies_available', models.IntegerField(default=1, verbose_name='Доступные экземпляры')),
                ('loan_records', models.JSONField(default=list, help_text="Список дат в формате ['YYYY-MM-DD', ...]", verbose_name='История выдачи')),
            ],
        ),
    ]
