# Generated by Django 5.2 on 2025-04-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='univercity',
            options={'verbose_name': 'Univer', 'verbose_name_plural': 'Univercity'},
        ),
        migrations.AddField(
            model_name='internship',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
